### ISSUE TITLE
Add Chinese translation

### ISSUE THREAD

**Issue by PBillingsby** [Developer-DAO/DAO-job-board#179]
### Overview
Add Chinese translation to job board

### Task
- [ ] Add language directory in `packages/client/public/locales` named by language code: English = `/en`, Chinese = `/zh`
- [ ] Add `common.json`
- [ ] Translate values from `packages/client/public/locales/en/common.json` matching the nesting of JSON to your created `common.json`
### Notes
- For now, to test add language code to url to view: `localhost:3000/zh`
- Server must be restarted after adding new JSON file
