### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by 7i7o** [Developer-DAO/DAO-job-board#213]
### Overview

Add Spanish translation to job board

### Task

- [ ] Add language directory in `packages/client/public/locales` named by language code: English = `/en`, Spanish = `/es`
- [ ] Add `common.json`
- [ ] Translate values from `packages/client/public/locales/en/common.json` matching the nesting of JSON to your created `common.json`

### Notes

- For now, to test add language code to url to view: `localhost:3000/es`
- Server must be restarted after adding new JSON file
